version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
    ports:
      - "54325:5432"

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
#    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db