"""some comment

Revision ID: 7bcb711912d3
Revises: 
Create Date: 2023-08-26 00:28:03.666039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcb711912d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('link', sa.String(), nullable=True),
        sa.Column('short_link', sa.String(), nullable=True),
        sa.Column('total_clicks', sa.Integer(), nullable=True),
        sa.Column('creation_date', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_link'), 'links', ['link'], unique=False)
    op.create_index(op.f('ix_links_short_link'), 'links', ['short_link'], unique=False)
    op.create_index(op.f('ix_links_total_clicks'), 'links', ['total_clicks'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_total_clicks'), table_name='links')
    op.drop_index(op.f('ix_links_short_link'), table_name='links')
    op.drop_index(op.f('ix_links_link'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
